### ISSUE TITLE
[バグ][UI/UX]ゲームプレイエリアがボタン操作時に微妙にズレる問題

### ISSUE THREAD

**Issue by gp-n-suzuki** [ohnokenichirou/tetris#9]
###  問題の概要
ゲームスタート、一時停止/再開、リスタート時にメインのゲームプレイエリア（キャンバス）が微妙にズレて、視覚的な違和感を生じさせています。

###  再現手順
1. ページを読み込む
2. 「ゲームスタート」ボタンをクリック
3. ゲームプレイエリアの位置を観察
4. 「一時停止」ボタンをクリック → 「再開」ボタンをクリック
5. ゲームプレイエリアの位置を観察
6. ゲームオーバーになった後、「Restart」ボタンをクリック
7. ゲームプレイエリアの位置を観察

###  期待される動作
- ボタン操作に関わらず、ゲームプレイエリア（キャンバス）の位置が常に固定されている
- UIの操作によってレイアウトが変動しない

###  実際の動作
- 「ゲームスタート」ボタンクリック時：スタートボタンが非表示になり、一時停止ボタンが表示されることでキャンバス位置がズレる
- 「一時停止」「再開」ボタン切り替え時：ボタンテキストの文字数の違い（"一時停止" vs "再開"）によってボタン幅が変わり、キャンバス位置がズレる
- リスタート時：ゲームオーバー画面の非表示とボタンテキストのリセットでキャンバス位置がズレる

###  根本原因
1. **ボタンの動的表示/非表示切り替え**
   ```javascript
   document.getElementById('startButton').style.display = 'none';
   document.getElementById('pauseButton').style.display = 'block';
   ```

2. **ボタンテキストの動的変更による幅の変化**
   ```javascript
   button.innerText = paused ? '再開' : '一時停止';
   ```

3. **Flexboxレイアウトの再計算**
   - `body`要素が`display: flex; justify-content: center; align-items: center;`
   - 子要素の変更が中央配置の基準点を変える

###  提案される解決策
1. **ボタン幅の固定化**
   ```css
   #pauseButton {
       width: 120px; /* 固定幅 */
   }
   ```

2. **visibilityプロパティの使用**
   ```javascript
   // display: none の代わりに
   element.style.visibility = 'hidden'; // レイアウト空間は保持
   ```

3. **絶対位置指定の検討**
   ```css
   #tetris {
       position: absolute;
       top: 50%;
       left: 50%;
       transform: translate(-50%, -50%);
   }
   ```

###  環境
- ブラウザ：すべて

###  関連ファイル
- `index.html` - HTMLレイアウト構造
- `style.css` - CSSスタイリング
- `script.js` - ボタン制御ロジック
